# SHELL
set-option -g default-shell /bin/bash

# TRUE COLOR
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# PREFIX
set -g prefix C-b

# CONFIGS
set  -g base-index           1
setw -g pane-base-index      1
set  -g status-keys          vi
set  -g mode-keys            vi
set  -g mouse                on
set  -g focus-events         off
setw -g aggressive-resize    off
setw -g clock-mode-style     24
set  -s escape-time          500
set  -g history-limit        2000
set  -g status-position      bottom
set  -s escape-time          0
set  -g extended-keys        on
set  -g extended-keys-format csi-u
set  -g allow-passthrough    all

# AUTO RENAME
set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# RELOAD
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# WINDOWS
bind t new-window -c "#{pane_current_path}"
bind x confirm-before -p "kill-window #W?" kill-window

# PANES
bind w confirm-before -p "kill-pane #P?" kill-pane
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# CLEAR 
bind l send-keys C-l
bind k clear-history
bind -n M-l send-keys C-l
bind -n M-k clear-history
